version: 2.1
jobs:
  test:
    docker:
      - image: node:20.5.1

    steps:
      - checkout

      # Restore cached dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      # Run Tests
      - run: npm test

      # Run Linter
      - run: npm run lint

  build:
    docker:
      - image: node:20.5.1

    steps:
      - checkout

      # Restore cached dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      # Build
      - run: npm run build

      # Deploy
      - run: './node_modules/.bin/firebase deploy --only hosting --token=$FIREBASE_TOKEN'

      # Save dependencies cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  build_and_test:
    jobs:
      - test
      - build
