version: 2
jobs:
  build:
    docker:
      - image: node:20.5.1

    steps:
      #Download dependencies
      - checkout

      #Cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
        
      #Install dependencies
      - run: 
      name: Install Dependencies
      command: install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      #Tests
      - run: 
      name: Run Tests
      command: npm test

      #Linter
      - run:
      name: Run Linter
      command: npm lint

      #Build
      - run: Build
      command: npm run build
