version: 2
jobs:
  build:
    docker:
      - image: node:20.5.1

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      #Install dependencies
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      #Run Tests
      - run: npm test

      #Run Linter
      - run: npm run lint

      #Build
      - run: npm run build